### ISSUE TITLE
请问博主是如何解决图片路径问题的？

### ISSUE THREAD

**Issue by ymyguang** [zu1k/blog#2]
1. 看了博主public的生成文件，看上去很简洁，结构也很清晰。自己生成的文件很乱，posts中的内容都被放了根目录。

2. 目前自己博客图片是用的图床，**但是看到博主没有使用图床却实现了本地预览和网页预览都能找到图片位置**，很是好奇，尽管在网上找了很多资料但还是无法实现。博主方便介绍指点一下是如何实现的吗？

**Comment by zu1k** [comment]
抱歉刚刚看到这个issue，不知道你的问题解决了没有

针对你说的第一个问题，我不太清楚你说的什么意思，我没有遇到过，如果方便贴一下你的配置文件吧

第二个问题很简单，我用的markdown的图片语法 `![描述](图片路径)` 而不是hexo或者hugo的专用语法

**Comment by ymyguang** [comment]
我也是写的markdown语法，在typora可以正常预览，但是一旦部署之后，就找不到图片了；
附地址(完全按照您的改的博客文件修改的   :>)
https://github.com/ymyguang/blog

**Comment by zu1k** [comment]
你的 Permalinks 写的有问题

**Comment by ymyguang** [comment]
修改了Permalinks之后，两个问题都解决了。多谢了
